### ISSUE TITLE
make project2a failed

### ISSUE THREAD

**Issue by justinxu9905** [1797818494/tinykv#9]
Thanks for sharing this amazing project! 

just found a potential issue. I tried to run the command `make project2a` and got this error message: 

> --- FAIL: TestLeaderStartReplication2AB (0.00s)
> panic: not a message to append noop entry [recovered]
> 	panic: not a message to append noop entry
> 
> goroutine 23 [running]:
> testing.tRunner.func1.2({0x62cd00, 0x6c4420})
> 	/usr/local/go/src/testing/testing.go:1526 +0x24e
> testing.tRunner.func1()
> 	/usr/local/go/src/testing/testing.go:1529 +0x39f
> panic({0x62cd00, 0x6c4420})
> 	/usr/local/go/src/runtime/panic.go:884 +0x213
> github.com/pingcap-incubator/tinykv/raft.commitNoopEntry(0xc00013a4b0, 0x7df520?)
> 	/home/zxu/tinykv/tinykv/raft/raft_paper_test.go:908 +0x425
> github.com/pingcap-incubator/tinykv/raft.TestLeaderStartReplication2AB(0xc000082d00)
> 	/home/zxu/tinykv/tinykv/raft/raft_paper_test.go:370 +0x1fc
> testing.tRunner(0xc000082d00, 0x684a10)
> 	/usr/local/go/src/testing/testing.go:1576 +0x10b
> created by testing.(*T).Run
> 	/usr/local/go/src/testing/testing.go:1629 +0x3ea
> FAIL	github.com/pingcap-incubator/tinykv/raft	0.563s
> FAIL
> make: *** [Makefile:60: project2a] Error 1

It is greatly appreciated if you can take a look

**Comment by 1797818494** [comment]
Sorry, the project still have bugs and its test should be rebuiled.
